### PR TITLE
Fixing SoulCage spawn limit

### PR DESCRIPTION
**Pull request by julian-piehl**
Fixing #35

### CODE REVIEW

**Comment by CodexAdrian** [comment]
Im honestly not sure if this should even be changed. While I understand the logic behind changing this code, it will definitely hurt performance, which is not ideal. idk, I'm going to request the opinions of the other 2 devs on this project

**Comment by julian-piehl** [comment]
I get your point.
However I don't think 3 more mobs should effect the performance noticable.

But if you won't change this code I would recommend changing the tiers and the documentation of the tiers so they won't try to spawn more then 6 mobs.
First time using tier 4 I thought I did something wrong because I read it should be 9 mobs.

**Review by MsRandom — APPROVED** [review]
Honestly, I think 7/9 would probably be fine, not much more than 6, so I don't see much of an issue with this

**Review by ThatGravyBoat — COMMENTED** [review]
While I do get why this needs to exist I don't think it should just be the spawn count I believe it should be either a new field or the spawn count with a clamp of like max 10 as that check is explicitly for performance reasons and with this change it would allow you to have more mobs just sitting there while it spawns more and possibly more than 9 if a modpack changes the spawn count of a tier.

**Comment by julian-piehl** [comment]
So you are saying I should be writing `l >= tier.spawnCount() || l > 10`?

But I think,
if I'm a modpack creator and I want to increase the spawn limit, I want it to actually be increased.
And if this causes lags, the spawn limit should be adjusted at the modpack.

**Comment by ThatGravyBoat** [comment]
Well thats why I said the first option too because where it would be a separate field in a soul shard tier for max spawn count because in my opinion they should be separated if it were to be increased because right now in this implementation its currently linked to spawn count which could mean mod pack creators would just increase it for the sake of having more be able to spawn in an area.

Also what I meant was this where it would make it so it would start out at whatever the tiers spawn count is but it would only let it go up to a max of 10 and when it hits that it would make it so it always hits the if statement. But the more I think about it the extra field for max spawn count is better.

```java
l >= Math.min(tier.spawnCount(), 10)
```

**Comment by CodexAdrian** [comment]
What I think I'll do is make a configurable max spawn count, and it'll do 

```Java
l >= Math.min(tier.spawnCount(), Config.maxSpawnCount)
```

**Comment by julian-piehl** [comment]
Oh... I just added some changes to accomplish the requirements of ThatGravyBoat.

**Pull request closed without merging**
